### ISSUE TITLE
Helper class is not thread safe

### ISSUE THREAD

**Issue by mariuslarsen** [livesamarthgupta/Github-Downloader#1]
[This](https://github.com/livesamarthgupta/Github-Downloader/blob/master/src/main/java/service/Helper.java#L24) is not a tread safe implementation of the singleton design pattern, as it is prone to race conditions.
You should take a look at 4 or 7 from https://www.journaldev.com/1377/java-singleton-design-pattern-best-practices-examples

**Comment by livesamarthgupta** [comment]
Thanks for reviewing the code so quickly, I will make the necessary changes. 🙂
